### PR TITLE
Reorganized htmls and scripts and added public logic in request

### PR DESCRIPTION
**Pull request by gleal42**
Changed file organization as well as htmls hrefs so that all htmls and scripts from requests are in public directory.
I tried adding ".." in the browser but it never goes back from root.
Anyways I added the protection just in case.

The base branch here is gl/feature/cgi so that differences are more easily analyzed.
But the PR is aimed at merging with master after cgi is approved and merged.

### CODE REVIEW

**Review by coderMeira — APPROVED** [review]
Sounds okay to mee :)

**Comment by mlrcbsousa** [comment]
> I tried adding ".." in the browser but it never goes back from root.

Is it because of the conditional we have in the code to block if the path starts with ".."

**Comment by gleal42** [comment]
> > I tried adding ".." in the browser but it never goes back from root.
> 
> Is it because of the conditional we have in the code to block if the path starts with ".."

No.
HTML resolves `localhost/../../` to `localhost/` so  `..` never appears in the request.

**Review by mlrcbsousa — APPROVED** [review]
LGTM!

**Pull request merged**
